In [ ]:
import tensorflow as tf

In [ ]:
tensor=tf.random.uniform(shape=(3,3),minval=0,maxval=1)

In [ ]:
print("Random Tensor:")
print(tensor)

Random Tensor:
tf.Tensor(
[[0.66937196 0.07039976 0.02282727]
 [0.3344338  0.6800175  0.12051952]
 [0.7615371  0.9443933  0.8080807 ]], shape=(3, 3), dtype=float32)


In [ ]:
A = tf.random.uniform((3, 3), minval=0, maxval=1)
B = tf.random.uniform((3, 3), minval=0, maxval=1)

In [ ]:
print("Tensor A:",A)
print("Tensor B:",B)

Tensor A: tf.Tensor(
[[0.5926987 0.2108258 0.8675983]
 [0.8741294 0.5579021 0.9113544]
 [0.8314235 0.5251937 0.7103102]], shape=(3, 3), dtype=float32)
Tensor B: tf.Tensor(
[[0.41633844 0.5784714  0.93455756]
 [0.24436903 0.9356115  0.560336  ]
 [0.00534594 0.8377658  0.85715127]], shape=(3, 3), dtype=float32)


In [ ]:
# Multiplication
mul_result = tf.matmul(A, B)
print("Matrix Multiplication (A x B):")
print(mul_result)

Matrix Multiplication (A x B):
tf.Tensor(
[[0.30292067 1.2669544  1.4157073 ]
 [0.5051397  1.79114    1.9107054 ]
 [0.47829193 1.5674056  1.6801414 ]], shape=(3, 3), dtype=float32)


In [ ]:
# Matrix Addition
add_result = tf.add(A, B)
print("Matrix Addition (A + B):")
print(add_result)

Matrix Addition (A + B):
tf.Tensor(
[[1.0090371  0.7892972  1.8021559 ]
 [1.1184984  1.4935136  1.4716904 ]
 [0.83676946 1.3629595  1.5674615 ]], shape=(3, 3), dtype=float32)


In [ ]:
# Transpose
transpose_A = tf.transpose(A)
print("Transpose of Tensor A:")
print(transpose_A)

Transpose of Tensor A:
tf.Tensor(
[[0.5926987 0.8741294 0.8314235]
 [0.2108258 0.5579021 0.5251937]
 [0.8675983 0.9113544 0.7103102]], shape=(3, 3), dtype=float32)


In [ ]:
tensor=tf.random.uniform(shape=(3,3),minval=0,maxval=1)
print("Original Tensor:",tensor)

Original Tensor: tf.Tensor(
[[0.541713   0.11838961 0.08291113]
 [0.9869473  0.27450132 0.02743149]
 [0.59155357 0.7327744  0.5182314 ]], shape=(3, 3), dtype=float32)


In [ ]:
numpy_array=tensor.numpy()
print("Converted Numpy array:",numpy_array)

Converted Numpy array: [[0.541713   0.11838961 0.08291113]
 [0.9869473  0.27450132 0.02743149]
 [0.59155357 0.7327744  0.5182314 ]]


In [ ]:
reshaped_tensor=tf.reshape(tensor,(1,9))
print("Reshaped Tensor:",reshaped_tensor)

Reshaped Tensor: tf.Tensor(
[[0.541713   0.11838961 0.08291113 0.9869473  0.27450132 0.02743149
  0.59155357 0.7327744  0.5182314 ]], shape=(1, 9), dtype=float32)
